services:
  attack-api:
    build: .
    ports:
      - 8080:8000
    environment:
      - SCOREBOARD_URL=${SCOREBOARD_URL:?Set Scoreboard URL}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
