services:
  attack-api:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8000
    environment:
      - SCOREBOARD_URL=${SCOREBOARD_URL:?Set Scoreboard URL}
    depends_on:
      attack-api-db:
        condition: service_healthy
  attack-api-db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
