services:
  attack-api:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8000
    environment:
      - SCOREBOARD_URL=${SCOREBOARD_URL:?Set Scoreboard URL}
      - CONTROLPANEL_URL=${CONTROLPANEL_URL:?Set Controlpanel URL}
    depends_on:
      attack-api-db:
        condition: service_healthy
  attack-api-db:
    image: postgres
    command: -N 500
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  db:
    name: attack-api-db
